<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:complexType name="as-contextType">
		<xs:sequence>
			<xs:element ref="auth-method"/>
			<xs:element ref="realm"/>
			<xs:element ref="required"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="auth-method" type="xs:string"/>
	<xs:element name="caller-propagation" type="xs:string"/>
	<xs:element name="confidentiality" type="xs:string"/>
	<xs:element name="connection-factory-name" type="xs:string"/>
	<xs:element name="container-size" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="destination-name" type="xs:string"/>
	<xs:element name="ejb-j2ee-engine">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="description" minOccurs="0"/>
				<xs:element name="enterprise-beans" type="enterprise-beansType" minOccurs="0"/>
				<xs:element name="transaction-descriptor" type="transaction-descriptorType" minOccurs="0"/>
				<xs:element name="security-permission" type="security-permissionType" minOccurs="0"/>
				<xs:element name="message-destination-maps" type="message-destination-mapsType" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ejb-local-refType">
		<xs:sequence>
			<xs:element ref="ejb-ref-name"/>
			<xs:element ref="jndi-name"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ejb-name" type="xs:string"/>
	<xs:complexType name="ejb-refType">
		<xs:sequence>
			<xs:element ref="ejb-ref-name"/>
			<xs:element ref="jndi-name"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ejb-ref-name" type="xs:string"/>
	<xs:complexType name="enterprise-beanType">
		<xs:sequence>
			<xs:element ref="ejb-name"/>
			<xs:element ref="jndi-name" minOccurs="0"/>
			<xs:element ref="container-size" minOccurs="0"/>
			<xs:element name="ejb-ref" type="ejb-refType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ejb-local-ref" type="ejb-local-refType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="resource-ref" type="resource-refType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="resource-env-ref" type="resource-env-refType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="server-component-ref" type="server-component-refType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="run-as-identity-map" type="run-as-identity-mapType" minOccurs="0"/>
			<xs:element name="ior-security-config" type="ior-security-configType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:choice minOccurs="0">
				<xs:element name="session-props" type="session-propsType"/>
				<xs:element name="entity-props" type="entity-propsType"/>
				<xs:element name="message-props" type="message-propsType"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="enterprise-beansType">
		<xs:sequence>
			<xs:element name="enterprise-bean" type="enterprise-beanType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="entity-propsType">
		<xs:sequence>
			<xs:element ref="unknown-pk-interval" minOccurs="0"/>
			<xs:element ref="initial-cache-size" minOccurs="0"/>
			<xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="establish-trust-in-client" type="xs:string"/>
	<xs:element name="establish-trust-in-target" type="xs:string"/>
	<xs:element name="group-name" type="xs:string"/>
	<xs:element name="initial-cache-size" type="xs:string"/>
	<xs:element name="integrity" type="xs:string"/>
	<xs:complexType name="ior-security-configType">
		<xs:sequence>
			<xs:element name="transport-config" type="transport-configType" minOccurs="0"/>
			<xs:element name="as-context" type="as-contextType" minOccurs="0"/>
			<xs:element name="sas-context" type="sas-contextType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="isolation-attribute" type="xs:string"/>
	<xs:complexType name="isolation-levelType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="method" type="methodType"/>
				<xs:element ref="ejb-name"/>
			</xs:choice>
			<xs:element ref="isolation-attribute"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="jndi-name" type="xs:string"/>
	<xs:element name="keeps-open-resources">
		<xs:complexType/>
	</xs:element>
	<xs:element name="lrulimit" type="xs:string"/>
	<xs:complexType name="message-propsType">
		<xs:sequence>
			<xs:element ref="destination-name" minOccurs="0"/>
			<xs:element ref="connection-factory-name" minOccurs="0"/>
			<xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="methodType">
		<xs:sequence>
			<xs:element ref="ejb-name"/>
			<xs:element ref="method-intf" minOccurs="0"/>
			<xs:element ref="method-name"/>
			<xs:element name="method-params" type="method-paramsType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="method-intf" type="xs:string"/>
	<xs:element name="method-name" type="xs:string"/>
	<xs:element name="method-param" type="xs:string"/>
	<xs:complexType name="method-paramsType">
		<xs:sequence>
			<xs:element ref="method-param" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="non-transactional">
		<xs:complexType/>
	</xs:element>
	<xs:complexType name="passivationType">
		<xs:sequence>
			<xs:element ref="passive-timeout"/>
			<xs:element ref="lrulimit"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="passive-timeout" type="xs:string"/>
	<xs:complexType name="propertyType">
		<xs:sequence>
			<xs:element ref="property-name"/>
			<xs:element ref="property-value"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="property-name" type="xs:string"/>
	<xs:element name="property-value" type="xs:string"/>
	<xs:element name="realm" type="xs:string"/>
	<xs:element name="required" type="xs:string"/>
	<xs:element name="res-link" type="xs:string"/>
	<xs:element name="res-ref-name" type="xs:string"/>
	<xs:complexType name="resource-env-refType">
		<xs:sequence>
			<xs:element ref="resource-env-ref-name"/>
			<xs:element ref="jndi-name"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="resource-env-ref-name" type="xs:string"/>
	<xs:complexType name="resource-refType">
		<xs:sequence>
			<xs:element ref="res-ref-name"/>
			<xs:element ref="res-link" minOccurs="0"/>
			<xs:element ref="non-transactional" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="role-name" type="xs:string"/>
	<xs:complexType name="run-as-identity-mapType">
		<xs:sequence>
			<xs:element ref="user-name"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sas-contextType">
		<xs:sequence>
			<xs:element ref="caller-propagation"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="security-permissionType">
		<xs:sequence>
			<xs:element name="security-role-map" type="security-role-mapType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="security-role-mapType">
		<xs:sequence>
			<xs:element ref="role-name"/>
			<xs:choice>
				<xs:sequence>
					<xs:element ref="user-name" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element ref="group-name" minOccurs="0" maxOccurs="unbounded"/>
				</xs:sequence>
				<xs:element ref="server-role-name" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="message-destination-mapsType">
		<xs:sequence>
			<xs:element name="message-destination" type="message-destinationType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="message-destination-name" type="xs:string"/>
	<xs:complexType name="message-destinationType">
		<xs:sequence>
			<xs:element ref="message-destination-name"/>
			<xs:element ref="jndi-name"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="server-component-refType">
		<xs:sequence>
			<xs:element ref="description" minOccurs="0"/>
			<xs:element ref="name"/>
			<xs:element ref="type"/>
			<xs:element ref="jndi-name"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="server-role-name" type="xs:string"/>
	<xs:complexType name="session-propsType">
		<xs:sequence>
			<xs:element ref="session-timeout" minOccurs="0"/>
			<xs:choice minOccurs="0">
				<xs:element name="passivation" type="passivationType"/>
				<xs:element ref="keeps-open-resources"/>
			</xs:choice>
			<xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="session-timeout" type="xs:string"/>
	<xs:complexType name="transaction-descriptorType">
		<xs:sequence>
			<xs:element name="isolation-level" type="isolation-levelType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="transport-configType">
		<xs:sequence>
			<xs:element ref="integrity"/>
			<xs:element ref="confidentiality"/>
			<xs:element ref="establish-trust-in-target"/>
			<xs:element ref="establish-trust-in-client"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="type" type="xs:string"/>
	<xs:element name="unknown-pk-interval" type="xs:string"/>
	<xs:element name="user-name" type="xs:string"/>
</xs:schema>
