<!ELEMENT persistent-ejb-map (switch-off-verification?, create-tables-at-deploy?, locking?, db-properties?, entity-beans?, relationships?)>

  <!ELEMENT switch-off-verification EMPTY>

  <!ELEMENT create-tables-at-deploy EMPTY>
 
  <!ELEMENT locking EMPTY>
  <!ATTLIST locking type (Administrative|Table|Local)  "Table">

  <!-- properties are valid for db-mapping of the entire abstract schema -->
  <!ELEMENT db-properties (data-source-name, database-vendor?)>
    <!ELEMENT data-source-name (#PCDATA)>
    
    <!-- database vendor name: DB2_UDB, DB2_UDB_AS400, DB2_UDB_OS390, MS_SQL_SERVER, ORACLE, SAPDB -->
    <!ELEMENT database-vendor EMPTY>
    <!ATTLIST database-vendor name (DB2_UDB|DB2_UDB_AS400|DB2_UDB_OS390|MS_SQL_SERVER|ORACLE|SAPDB|SYBASE) #REQUIRED>

  <!ELEMENT entity-beans (entity-bean+)>
    <!ELEMENT entity-bean (ejb-name, table-name, (read-only | select-for-update)?, field-map*, finder-descriptor*)>
      <!ELEMENT ejb-name (#PCDATA)>

      <!-- name of the table which is going to be used from this ejb -->
      <!ELEMENT table-name (#PCDATA)>

      <!-- exists if bean will update nothing in DB, only reads  -->
      <!ELEMENT read-only EMPTY>

      <!ELEMENT select-for-update EMPTY>

      <!ELEMENT field-map (field-name, (column|dv-column+), mutable?)>
      <!ELEMENT mutable EMPTY>

      <!ATTLIST field-map key-type (NoKey|PrimaryKey|UniqueKey) "NoKey">

	<!-- tag exists if cmp is mapped to a single column in DB; 
	     it is possible if cmp is not dependent value field or if it is dependent value SERIALIZED_OBJ,
	     i.e. serialized object mapped to a byte[] in database -->
	<!ELEMENT column (column-name)>

	<!-- describes db-mapping for a public field of dependent-value class -->
	<!ELEMENT dv-column (subfield-name, column-name)>

        <!-- name of field in the dependent value class which is described -->
	<!ELEMENT subfield-name (#PCDATA)>

	<!-- name of column in the table to which this cmp-field is mapped -->
	<!ELEMENT column-name (#PCDATA)>

	<!-- name of the cmp-field which mapping is described -->
	<!ELEMENT field-name (#PCDATA)>

        <!-- tag is used to describe SQL statements for find methods of CMP1.x entity beans or SQL statements 
	     for find methods of CMP2.x entity beans which differ from the conventional SQL statements 
	     generated by the QL-translator -->
	<!ELEMENT finder-descriptor (criteria?, method-name, method-params, switch-off-storing?, load-selected-objects?, lazy-loading?, fetch-size?, ql-2.1-compatible?)>
	
	  <!-- the whole SQL select statement which is going to be executed in this find method --> 
	  <!ELEMENT criteria (#PCDATA)>

	  <!-- name of this find method --> 
	  <!ELEMENT method-name (#PCDATA)>

	  <!-- parameters of this find method --> 
	  <!ELEMENT method-params (method-param*)>
	    <!ELEMENT method-param (#PCDATA)>
	    
	  <!--  switches off storing before this find/select method --> 
	  <!ELEMENT switch-off-storing EMPTY>

          <!ELEMENT load-selected-objects EMPTY>
          <!ATTLIST load-selected-objects lock (read|write) #IMPLIED>

	  <!--  lazy loading strategy is switched on for this find/select method --> 
	  <!ELEMENT lazy-loading EMPTY>

	  <!--  the given fetch-size is used when loading the selected objects for this find/select method --> 
          <!ELEMENT fetch-size (#PCDATA)>

          <!-- if tag exists then query is considered as QL 2.1 compatible;
	       the value of the tag is taken into account only if the specified method is EJB2.0 find or select method -->
	  <!ELEMENT ql-2.1-compatible EMPTY>

  <!ELEMENT relationships (table-relation*)>
    <!ELEMENT table-relation (help-table?, table-relationship-role, table-relationship-role)>
      
      <!-- in case of M:M relation, it is obligatory to use help table; 
           tag exists if M:M relationship is described and the tag's value is the name of this help table -->
      <!ELEMENT help-table (#PCDATA)>
      <!ELEMENT table-relationship-role (ejb-name, cmr-field?, fk-column*)>
      <!ATTLIST table-relationship-role key-type (NoKey|PrimaryKey|ForeignKey) "PrimaryKey">

        <!-- if key-type is NoKey or ForeignKey then tag is used to describe (logical)foreign
	     key column and its reference to the correspondig pk cmp-field --> 
        <!ELEMENT fk-column (column-name, pk-field-name)>

           <!-- name of the referenced pk cmp-field -->
	   <!ELEMENT pk-field-name (#PCDATA)>

	<!-- name of cmr-field which mapping is represented; tag does not exist if uni-directional 
	     relationship is described and if this table-relationship-role element describes those part
	     of the ralation which has no cmr-field -->
	<!ELEMENT cmr-field (#PCDATA)>




