//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.31 at 11:21:41 AM MSK 
//


package adaptermetadata;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}GuiHandlerClassName"/>
 *         &lt;element ref="{}Type"/>
 *         &lt;element ref="{}GuiLabels"/>
 *         &lt;element ref="{}Outbound"/>
 *         &lt;element ref="{}Inbound"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}Attribute"/>
 *           &lt;element ref="{}AttributeTable"/>
 *           &lt;element ref="{}DynamicAttributes"/>
 *         &lt;/choice>
 *         &lt;element ref="{}TabDefinition" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "guiHandlerClassName",
    "type",
    "guiLabels",
    "outbound",
    "inbound",
    "attributeOrAttributeTableOrDynamicAttributes",
    "tabDefinition"
})
@XmlRootElement(name = "AdapterTypeMetaData")
public class AdapterTypeMetaData {

    @XmlElement(name = "GuiHandlerClassName", required = true)
    protected GuiHandlerClassName guiHandlerClassName;
    @XmlElement(name = "Type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;
    @XmlElement(name = "GuiLabels", required = true)
    protected GuiLabels guiLabels;
    @XmlElement(name = "Outbound", required = true)
    protected Outbound outbound;
    @XmlElement(name = "Inbound", required = true)
    protected Inbound inbound;
    @XmlElements({
        @XmlElement(name = "Attribute", type = Attribute.class),
        @XmlElement(name = "AttributeTable", type = AttributeTable.class),
        @XmlElement(name = "DynamicAttributes", type = DynamicAttributes.class)
    })
    protected List<Object> attributeOrAttributeTableOrDynamicAttributes;
    @XmlElement(name = "TabDefinition", required = true)
    protected List<TabDefinition> tabDefinition;
    @XmlAttribute(name = "version", required = true)
    protected BigInteger version;

    /**
     * Gets the value of the guiHandlerClassName property.
     * 
     * @return
     *     possible object is
     *     {@link GuiHandlerClassName }
     *     
     */
    public GuiHandlerClassName getGuiHandlerClassName() {
        return guiHandlerClassName;
    }

    /**
     * Sets the value of the guiHandlerClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuiHandlerClassName }
     *     
     */
    public void setGuiHandlerClassName(GuiHandlerClassName value) {
        this.guiHandlerClassName = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the guiLabels property.
     * 
     * @return
     *     possible object is
     *     {@link GuiLabels }
     *     
     */
    public GuiLabels getGuiLabels() {
        return guiLabels;
    }

    /**
     * Sets the value of the guiLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuiLabels }
     *     
     */
    public void setGuiLabels(GuiLabels value) {
        this.guiLabels = value;
    }

    /**
     * Gets the value of the outbound property.
     * 
     * @return
     *     possible object is
     *     {@link Outbound }
     *     
     */
    public Outbound getOutbound() {
        return outbound;
    }

    /**
     * Sets the value of the outbound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outbound }
     *     
     */
    public void setOutbound(Outbound value) {
        this.outbound = value;
    }

    /**
     * Gets the value of the inbound property.
     * 
     * @return
     *     possible object is
     *     {@link Inbound }
     *     
     */
    public Inbound getInbound() {
        return inbound;
    }

    /**
     * Sets the value of the inbound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inbound }
     *     
     */
    public void setInbound(Inbound value) {
        this.inbound = value;
    }

    /**
     * Gets the value of the attributeOrAttributeTableOrDynamicAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeOrAttributeTableOrDynamicAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeOrAttributeTableOrDynamicAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * {@link AttributeTable }
     * {@link DynamicAttributes }
     * 
     * 
     */
    public List<Object> getAttributeOrAttributeTableOrDynamicAttributes() {
        if (attributeOrAttributeTableOrDynamicAttributes == null) {
            attributeOrAttributeTableOrDynamicAttributes = new ArrayList<Object>();
        }
        return this.attributeOrAttributeTableOrDynamicAttributes;
    }

    /**
     * Gets the value of the tabDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tabDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTabDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TabDefinition }
     * 
     * 
     */
    public List<TabDefinition> getTabDefinition() {
        if (tabDefinition == null) {
            tabDefinition = new ArrayList<TabDefinition>();
        }
        return this.tabDefinition;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

}
