//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.29 at 07:50:51 AM MSK 
//


package adaptermetadata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}EditCondition"/>
 *           &lt;element ref="{}OrCondition"/>
 *         &lt;/choice>
 *         &lt;element ref="{}NotCondition" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "editConditionOrOrCondition",
    "notCondition"
})
@XmlRootElement(name = "AndCondition")
public class AndCondition {

    @XmlElements({
        @XmlElement(name = "EditCondition", type = EditCondition.class),
        @XmlElement(name = "OrCondition", type = OrCondition.class)
    })
    protected List<Object> editConditionOrOrCondition;
    @XmlElement(name = "NotCondition")
    protected NotCondition notCondition;

    /**
     * Gets the value of the editConditionOrOrCondition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the editConditionOrOrCondition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEditConditionOrOrCondition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EditCondition }
     * {@link OrCondition }
     * 
     * 
     */
    public List<Object> getEditConditionOrOrCondition() {
        if (editConditionOrOrCondition == null) {
            editConditionOrOrCondition = new ArrayList<Object>();
        }
        return this.editConditionOrOrCondition;
    }

    /**
     * Gets the value of the notCondition property.
     * 
     * @return
     *     possible object is
     *     {@link NotCondition }
     *     
     */
    public NotCondition getNotCondition() {
        return notCondition;
    }

    /**
     * Sets the value of the notCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotCondition }
     *     
     */
    public void setNotCondition(NotCondition value) {
        this.notCondition = value;
    }

}
