//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.29 at 07:50:51 AM MSK 
//


package adaptermetadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ReferenceName"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{}EditCondition"/>
 *           &lt;element ref="{}NotCondition"/>
 *           &lt;element ref="{}OrCondition"/>
 *           &lt;element ref="{}AndCondition"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "referenceName",
    "editCondition",
    "notCondition",
    "orCondition",
    "andCondition"
})
@XmlRootElement(name = "AttributeReference")
public class AttributeReference {

    @XmlElement(name = "ReferenceName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String referenceName;
    @XmlElement(name = "EditCondition")
    protected EditCondition editCondition;
    @XmlElement(name = "NotCondition")
    protected NotCondition notCondition;
    @XmlElement(name = "OrCondition")
    protected OrCondition orCondition;
    @XmlElement(name = "AndCondition")
    protected AndCondition andCondition;

    /**
     * Gets the value of the referenceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceName() {
        return referenceName;
    }

    /**
     * Sets the value of the referenceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceName(String value) {
        this.referenceName = value;
    }

    /**
     * Gets the value of the editCondition property.
     * 
     * @return
     *     possible object is
     *     {@link EditCondition }
     *     
     */
    public EditCondition getEditCondition() {
        return editCondition;
    }

    /**
     * Sets the value of the editCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditCondition }
     *     
     */
    public void setEditCondition(EditCondition value) {
        this.editCondition = value;
    }

    /**
     * Gets the value of the notCondition property.
     * 
     * @return
     *     possible object is
     *     {@link NotCondition }
     *     
     */
    public NotCondition getNotCondition() {
        return notCondition;
    }

    /**
     * Sets the value of the notCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotCondition }
     *     
     */
    public void setNotCondition(NotCondition value) {
        this.notCondition = value;
    }

    /**
     * Gets the value of the orCondition property.
     * 
     * @return
     *     possible object is
     *     {@link OrCondition }
     *     
     */
    public OrCondition getOrCondition() {
        return orCondition;
    }

    /**
     * Sets the value of the orCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrCondition }
     *     
     */
    public void setOrCondition(OrCondition value) {
        this.orCondition = value;
    }

    /**
     * Gets the value of the andCondition property.
     * 
     * @return
     *     possible object is
     *     {@link AndCondition }
     *     
     */
    public AndCondition getAndCondition() {
        return andCondition;
    }

    /**
     * Sets the value of the andCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link AndCondition }
     *     
     */
    public void setAndCondition(AndCondition value) {
        this.andCondition = value;
    }

}
