//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.31 at 11:21:41 AM MSK 
//


package adaptermetadata;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}Usage" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}Flag"/>
 *           &lt;element ref="{}GuiLabels"/>
 *           &lt;element ref="{}DataType"/>
 *           &lt;element ref="{}Default"/>
 *           &lt;element ref="{}FixedValue"/>
 *           &lt;element ref="{}HelpService"/>
 *           &lt;element ref="{}Length"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="isPassword" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "usage",
    "flagOrGuiLabelsOrDataType"
})
@XmlRootElement(name = "Attribute")
public class Attribute {

    @XmlElement(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlElement(name = "Usage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String usage;
    @XmlElementRefs({
        @XmlElementRef(name = "FixedValue", type = FixedValue.class, required = false),
        @XmlElementRef(name = "Length", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "HelpService", type = HelpService.class, required = false),
        @XmlElementRef(name = "DataType", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Flag", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "GuiLabels", type = GuiLabels.class, required = false),
        @XmlElementRef(name = "Default", type = JAXBElement.class, required = false)
    })
    protected List<Object> flagOrGuiLabelsOrDataType;
    @XmlAttribute(name = "isPassword")
    protected Boolean isPassword;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsage(String value) {
        this.usage = value;
    }

    /**
     * Gets the value of the flagOrGuiLabelsOrDataType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flagOrGuiLabelsOrDataType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlagOrGuiLabelsOrDataType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FixedValue }
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link HelpService }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link GuiLabels }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getFlagOrGuiLabelsOrDataType() {
        if (flagOrGuiLabelsOrDataType == null) {
            flagOrGuiLabelsOrDataType = new ArrayList<Object>();
        }
        return this.flagOrGuiLabelsOrDataType;
    }

    /**
     * Gets the value of the isPassword property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPassword() {
        return isPassword;
    }

    /**
     * Sets the value of the isPassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPassword(Boolean value) {
        this.isPassword = value;
    }

}
