//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.31 at 11:21:41 AM MSK 
//


package adaptermetadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}HelpServiceName"/>
 *         &lt;element ref="{}HelpServiceQueryAttributes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "helpServiceName",
    "helpServiceQueryAttributes"
})
@XmlRootElement(name = "HelpService")
public class HelpService {

    @XmlElement(name = "HelpServiceName", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String helpServiceName;
    @XmlElement(name = "HelpServiceQueryAttributes", required = true)
    protected HelpServiceQueryAttributes helpServiceQueryAttributes;

    /**
     * Gets the value of the helpServiceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHelpServiceName() {
        return helpServiceName;
    }

    /**
     * Sets the value of the helpServiceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHelpServiceName(String value) {
        this.helpServiceName = value;
    }

    /**
     * Gets the value of the helpServiceQueryAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link HelpServiceQueryAttributes }
     *     
     */
    public HelpServiceQueryAttributes getHelpServiceQueryAttributes() {
        return helpServiceQueryAttributes;
    }

    /**
     * Sets the value of the helpServiceQueryAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link HelpServiceQueryAttributes }
     *     
     */
    public void setHelpServiceQueryAttributes(HelpServiceQueryAttributes value) {
        this.helpServiceQueryAttributes = value;
    }

}
