//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.31 at 11:21:41 AM MSK 
//


package adaptermetadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ModuleSequence"/>
 *         &lt;element ref="{}ModuleConfig"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "moduleSequence",
    "moduleConfig"
})
@XmlRootElement(name = "ModuleProcessorAttributes")
public class ModuleProcessorAttributes {

    @XmlElement(name = "ModuleSequence", required = true)
    protected ModuleSequence moduleSequence;
    @XmlElement(name = "ModuleConfig", required = true)
    protected ModuleConfig moduleConfig;

    /**
     * Gets the value of the moduleSequence property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleSequence }
     *     
     */
    public ModuleSequence getModuleSequence() {
        return moduleSequence;
    }

    /**
     * Sets the value of the moduleSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleSequence }
     *     
     */
    public void setModuleSequence(ModuleSequence value) {
        this.moduleSequence = value;
    }

    /**
     * Gets the value of the moduleConfig property.
     * 
     * @return
     *     possible object is
     *     {@link ModuleConfig }
     *     
     */
    public ModuleConfig getModuleConfig() {
        return moduleConfig;
    }

    /**
     * Sets the value of the moduleConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModuleConfig }
     *     
     */
    public void setModuleConfig(ModuleConfig value) {
        this.moduleConfig = value;
    }

}
