//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.29 at 07:50:51 AM MSK 
//


package adaptermetadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}EditCondition"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "editCondition"
})
@XmlRootElement(name = "NotCondition")
public class NotCondition {

    @XmlElement(name = "EditCondition", required = true)
    protected EditCondition editCondition;

    /**
     * Gets the value of the editCondition property.
     * 
     * @return
     *     possible object is
     *     {@link EditCondition }
     *     
     */
    public EditCondition getEditCondition() {
        return editCondition;
    }

    /**
     * Sets the value of the editCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditCondition }
     *     
     */
    public void setEditCondition(EditCondition value) {
        this.editCondition = value;
    }

}
