//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.29 at 07:50:51 AM MSK 
//


package adaptermetadata;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the adaptermetadata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AttributeValue_QNAME = new QName("", "AttributeValue");
    private final static QName _Usage_QNAME = new QName("", "Usage");
    private final static QName _Flag_QNAME = new QName("", "Flag");
    private final static QName _Default_QNAME = new QName("", "Default");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _Type_QNAME = new QName("", "Type");
    private final static QName _HelpServiceName_QNAME = new QName("", "HelpServiceName");
    private final static QName _Length_QNAME = new QName("", "Length");
    private final static QName _Version_QNAME = new QName("", "Version");
    private final static QName _DataType_QNAME = new QName("", "DataType");
    private final static QName _AttributeName_QNAME = new QName("", "AttributeName");
    private final static QName _Value_QNAME = new QName("", "value");
    private final static QName _ReferenceName_QNAME = new QName("", "ReferenceName");
    private final static QName _Key_QNAME = new QName("", "Key");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: adaptermetadata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NotCondition }
     * 
     */
    public NotCondition createNotCondition() {
        return new NotCondition();
    }

    /**
     * Create an instance of {@link EditCondition }
     * 
     */
    public EditCondition createEditCondition() {
        return new EditCondition();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link GuiLabels }
     * 
     */
    public GuiLabels createGuiLabels() {
        return new GuiLabels();
    }

    /**
     * Create an instance of {@link Label }
     * 
     */
    public Label createLabel() {
        return new Label();
    }

    /**
     * Create an instance of {@link FixedValue }
     * 
     */
    public FixedValue createFixedValue() {
        return new FixedValue();
    }

    /**
     * Create an instance of {@link HelpService }
     * 
     */
    public HelpService createHelpService() {
        return new HelpService();
    }

    /**
     * Create an instance of {@link HelpServiceQueryAttributes }
     * 
     */
    public HelpServiceQueryAttributes createHelpServiceQueryAttributes() {
        return new HelpServiceQueryAttributes();
    }

    /**
     * Create an instance of {@link HelpServiceQueryAttribute }
     * 
     */
    public HelpServiceQueryAttribute createHelpServiceQueryAttribute() {
        return new HelpServiceQueryAttribute();
    }

    /**
     * Create an instance of {@link AdapterTypeMetaData }
     * 
     */
    public AdapterTypeMetaData createAdapterTypeMetaData() {
        return new AdapterTypeMetaData();
    }

    /**
     * Create an instance of {@link GuiHandlerClassName }
     * 
     */
    public GuiHandlerClassName createGuiHandlerClassName() {
        return new GuiHandlerClassName();
    }

    /**
     * Create an instance of {@link Outbound }
     * 
     */
    public Outbound createOutbound() {
        return new Outbound();
    }

    /**
     * Create an instance of {@link TransportProtocol }
     * 
     */
    public TransportProtocol createTransportProtocol() {
        return new TransportProtocol();
    }

    /**
     * Create an instance of {@link ValidMessageProtocols }
     * 
     */
    public ValidMessageProtocols createValidMessageProtocols() {
        return new ValidMessageProtocols();
    }

    /**
     * Create an instance of {@link ProtocolIdentifier }
     * 
     */
    public ProtocolIdentifier createProtocolIdentifier() {
        return new ProtocolIdentifier();
    }

    /**
     * Create an instance of {@link ChannelAttributes }
     * 
     */
    public ChannelAttributes createChannelAttributes() {
        return new ChannelAttributes();
    }

    /**
     * Create an instance of {@link Tab }
     * 
     */
    public Tab createTab() {
        return new Tab();
    }

    /**
     * Create an instance of {@link AttributeReference }
     * 
     */
    public AttributeReference createAttributeReference() {
        return new AttributeReference();
    }

    /**
     * Create an instance of {@link OrCondition }
     * 
     */
    public OrCondition createOrCondition() {
        return new OrCondition();
    }

    /**
     * Create an instance of {@link AndCondition }
     * 
     */
    public AndCondition createAndCondition() {
        return new AndCondition();
    }

    /**
     * Create an instance of {@link AttributeGroup }
     * 
     */
    public AttributeGroup createAttributeGroup() {
        return new AttributeGroup();
    }

    /**
     * Create an instance of {@link SecurityAttributes }
     * 
     */
    public SecurityAttributes createSecurityAttributes() {
        return new SecurityAttributes();
    }

    /**
     * Create an instance of {@link MessageProtocol }
     * 
     */
    public MessageProtocol createMessageProtocol() {
        return new MessageProtocol();
    }

    /**
     * Create an instance of {@link ModuleProcessorAttributes }
     * 
     */
    public ModuleProcessorAttributes createModuleProcessorAttributes() {
        return new ModuleProcessorAttributes();
    }

    /**
     * Create an instance of {@link ModuleSequence }
     * 
     */
    public ModuleSequence createModuleSequence() {
        return new ModuleSequence();
    }

    /**
     * Create an instance of {@link ModuleSequenceItem }
     * 
     */
    public ModuleSequenceItem createModuleSequenceItem() {
        return new ModuleSequenceItem();
    }

    /**
     * Create an instance of {@link GlobalChannelAttributes }
     * 
     */
    public GlobalChannelAttributes createGlobalChannelAttributes() {
        return new GlobalChannelAttributes();
    }

    /**
     * Create an instance of {@link GlobalSecurityAttributes }
     * 
     */
    public GlobalSecurityAttributes createGlobalSecurityAttributes() {
        return new GlobalSecurityAttributes();
    }

    /**
     * Create an instance of {@link Inbound }
     * 
     */
    public Inbound createInbound() {
        return new Inbound();
    }

    /**
     * Create an instance of {@link AttributeTable }
     * 
     */
    public AttributeTable createAttributeTable() {
        return new AttributeTable();
    }

    /**
     * Create an instance of {@link DynamicAttributes }
     * 
     */
    public DynamicAttributes createDynamicAttributes() {
        return new DynamicAttributes();
    }

    /**
     * Create an instance of {@link TabDefinition }
     * 
     */
    public TabDefinition createTabDefinition() {
        return new TabDefinition();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AttributeValue")
    public JAXBElement<String> createAttributeValue(String value) {
        return new JAXBElement<String>(_AttributeValue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Usage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUsage(String value) {
        return new JAXBElement<String>(_Usage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Flag")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createFlag(String value) {
        return new JAXBElement<String>(_Flag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Default")
    public JAXBElement<String> createDefault(String value) {
        return new JAXBElement<String>(_Default_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HelpServiceName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createHelpServiceName(String value) {
        return new JAXBElement<String>(_HelpServiceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Length")
    public JAXBElement<BigInteger> createLength(BigInteger value) {
        return new JAXBElement<BigInteger>(_Length_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DataType")
    public JAXBElement<String> createDataType(String value) {
        return new JAXBElement<String>(_DataType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AttributeName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAttributeName(String value) {
        return new JAXBElement<String>(_AttributeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReferenceName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReferenceName(String value) {
        return new JAXBElement<String>(_ReferenceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Key")
    public JAXBElement<String> createKey(String value) {
        return new JAXBElement<String>(_Key_QNAME, String.class, null, value);
    }

}
