//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.31 at 11:21:41 AM MSK 
//


package adaptermetadata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TransportProtocol" maxOccurs="unbounded"/>
 *         &lt;element ref="{}MessageProtocol" maxOccurs="unbounded"/>
 *         &lt;element ref="{}GlobalChannelAttributes"/>
 *         &lt;element ref="{}GlobalSecurityAttributes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transportProtocol",
    "messageProtocol",
    "globalChannelAttributes",
    "globalSecurityAttributes"
})
@XmlRootElement(name = "Outbound")
public class Outbound {

    @XmlElement(name = "TransportProtocol", required = true)
    protected List<TransportProtocol> transportProtocol;
    @XmlElement(name = "MessageProtocol", required = true)
    protected List<MessageProtocol> messageProtocol;
    @XmlElement(name = "GlobalChannelAttributes", required = true)
    protected GlobalChannelAttributes globalChannelAttributes;
    @XmlElement(name = "GlobalSecurityAttributes", required = true)
    protected GlobalSecurityAttributes globalSecurityAttributes;

    /**
     * Gets the value of the transportProtocol property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportProtocol property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportProtocol().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransportProtocol }
     * 
     * 
     */
    public List<TransportProtocol> getTransportProtocol() {
        if (transportProtocol == null) {
            transportProtocol = new ArrayList<TransportProtocol>();
        }
        return this.transportProtocol;
    }

    /**
     * Gets the value of the messageProtocol property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageProtocol property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageProtocol().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageProtocol }
     * 
     * 
     */
    public List<MessageProtocol> getMessageProtocol() {
        if (messageProtocol == null) {
            messageProtocol = new ArrayList<MessageProtocol>();
        }
        return this.messageProtocol;
    }

    /**
     * Gets the value of the globalChannelAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalChannelAttributes }
     *     
     */
    public GlobalChannelAttributes getGlobalChannelAttributes() {
        return globalChannelAttributes;
    }

    /**
     * Sets the value of the globalChannelAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalChannelAttributes }
     *     
     */
    public void setGlobalChannelAttributes(GlobalChannelAttributes value) {
        this.globalChannelAttributes = value;
    }

    /**
     * Gets the value of the globalSecurityAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalSecurityAttributes }
     *     
     */
    public GlobalSecurityAttributes getGlobalSecurityAttributes() {
        return globalSecurityAttributes;
    }

    /**
     * Sets the value of the globalSecurityAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalSecurityAttributes }
     *     
     */
    public void setGlobalSecurityAttributes(GlobalSecurityAttributes value) {
        this.globalSecurityAttributes = value;
    }

}
