//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.31 at 11:21:41 AM MSK 
//


package adaptermetadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}Version"/>
 *         &lt;element ref="{}GuiLabels"/>
 *         &lt;element ref="{}ValidMessageProtocols"/>
 *         &lt;element ref="{}ChannelAttributes"/>
 *         &lt;element ref="{}SecurityAttributes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "version",
    "guiLabels",
    "validMessageProtocols",
    "channelAttributes",
    "securityAttributes"
})
@XmlRootElement(name = "TransportProtocol")
public class TransportProtocol {

    @XmlElement(name = "Name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;
    @XmlElement(name = "Version", required = true)
    protected String version;
    @XmlElement(name = "GuiLabels", required = true)
    protected GuiLabels guiLabels;
    @XmlElement(name = "ValidMessageProtocols", required = true)
    protected ValidMessageProtocols validMessageProtocols;
    @XmlElement(name = "ChannelAttributes", required = true)
    protected ChannelAttributes channelAttributes;
    @XmlElement(name = "SecurityAttributes", required = true)
    protected SecurityAttributes securityAttributes;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the guiLabels property.
     * 
     * @return
     *     possible object is
     *     {@link GuiLabels }
     *     
     */
    public GuiLabels getGuiLabels() {
        return guiLabels;
    }

    /**
     * Sets the value of the guiLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link GuiLabels }
     *     
     */
    public void setGuiLabels(GuiLabels value) {
        this.guiLabels = value;
    }

    /**
     * Gets the value of the validMessageProtocols property.
     * 
     * @return
     *     possible object is
     *     {@link ValidMessageProtocols }
     *     
     */
    public ValidMessageProtocols getValidMessageProtocols() {
        return validMessageProtocols;
    }

    /**
     * Sets the value of the validMessageProtocols property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidMessageProtocols }
     *     
     */
    public void setValidMessageProtocols(ValidMessageProtocols value) {
        this.validMessageProtocols = value;
    }

    /**
     * Gets the value of the channelAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link ChannelAttributes }
     *     
     */
    public ChannelAttributes getChannelAttributes() {
        return channelAttributes;
    }

    /**
     * Sets the value of the channelAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChannelAttributes }
     *     
     */
    public void setChannelAttributes(ChannelAttributes value) {
        this.channelAttributes = value;
    }

    /**
     * Gets the value of the securityAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityAttributes }
     *     
     */
    public SecurityAttributes getSecurityAttributes() {
        return securityAttributes;
    }

    /**
     * Sets the value of the securityAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityAttributes }
     *     
     */
    public void setSecurityAttributes(SecurityAttributes value) {
        this.securityAttributes = value;
    }

}
