//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:01:08 PM MSK 
//


package logConfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "destinationRefOrAnonymousDestination"
})
@XmlRootElement(name = "associated-destinations")
public class AssociatedDestinations {

    @XmlElements({
        @XmlElement(name = "destination-ref", type = DestinationRef.class),
        @XmlElement(name = "anonymous-destination", type = AnonymousDestination.class)
    })
    protected List<Object> destinationRefOrAnonymousDestination;

    /**
     * Gets the value of the destinationRefOrAnonymousDestination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destinationRefOrAnonymousDestination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestinationRefOrAnonymousDestination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DestinationRef }
     * {@link AnonymousDestination }
     * 
     * 
     */
    public List<Object> getDestinationRefOrAnonymousDestination() {
        if (destinationRefOrAnonymousDestination == null) {
            destinationRefOrAnonymousDestination = new ArrayList<Object>();
        }
        return this.destinationRefOrAnonymousDestination;
    }

}
