//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:52:46 AM MSK 
//


package logConfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "relativeSeverity",
    "associatedDestinations",
    "logFilters"
})
@XmlRootElement(name = "log-controller")
public class LogController {

    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String name;
    @XmlAttribute(name = "effective-severity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String effectiveSeverity;
    @XmlAttribute(name = "minimum-severity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String minimumSeverity;
    @XmlAttribute(name = "maximum-severity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String maximumSeverity;
    @XmlAttribute(name = "bundle-name")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String bundleName;
    @XmlAttribute(name = "db-log")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String dbLog;
    @XmlElement(name = "relative-severity")
    protected List<RelativeSeverity> relativeSeverity;
    @XmlElement(name = "associated-destinations")
    protected AssociatedDestinations associatedDestinations;
    @XmlElement(name = "log-filters")
    protected LogFilters logFilters;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the effectiveSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveSeverity() {
        return effectiveSeverity;
    }

    /**
     * Sets the value of the effectiveSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveSeverity(String value) {
        this.effectiveSeverity = value;
    }

    /**
     * Gets the value of the minimumSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimumSeverity() {
        return minimumSeverity;
    }

    /**
     * Sets the value of the minimumSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimumSeverity(String value) {
        this.minimumSeverity = value;
    }

    /**
     * Gets the value of the maximumSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximumSeverity() {
        return maximumSeverity;
    }

    /**
     * Sets the value of the maximumSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximumSeverity(String value) {
        this.maximumSeverity = value;
    }

    /**
     * Gets the value of the bundleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBundleName() {
        return bundleName;
    }

    /**
     * Sets the value of the bundleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBundleName(String value) {
        this.bundleName = value;
    }

    /**
     * Gets the value of the dbLog property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbLog() {
        return dbLog;
    }

    /**
     * Sets the value of the dbLog property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbLog(String value) {
        this.dbLog = value;
    }

    /**
     * Gets the value of the relativeSeverity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relativeSeverity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelativeSeverity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelativeSeverity }
     * 
     * 
     */
    public List<RelativeSeverity> getRelativeSeverity() {
        if (relativeSeverity == null) {
            relativeSeverity = new ArrayList<RelativeSeverity>();
        }
        return this.relativeSeverity;
    }

    /**
     * Gets the value of the associatedDestinations property.
     * 
     * @return
     *     possible object is
     *     {@link AssociatedDestinations }
     *     
     */
    public AssociatedDestinations getAssociatedDestinations() {
        return associatedDestinations;
    }

    /**
     * Sets the value of the associatedDestinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociatedDestinations }
     *     
     */
    public void setAssociatedDestinations(AssociatedDestinations value) {
        this.associatedDestinations = value;
    }

    /**
     * Gets the value of the logFilters property.
     * 
     * @return
     *     possible object is
     *     {@link LogFilters }
     *     
     */
    public LogFilters getLogFilters() {
        return logFilters;
    }

    /**
     * Sets the value of the logFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogFilters }
     *     
     */
    public void setLogFilters(LogFilters value) {
        this.logFilters = value;
    }

}
