//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:01:08 PM MSK 
//


package logConfiguration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "logFormatters",
    "logDestinations",
    "logControllers"
})
@XmlRootElement(name = "log-configuration")
public class LogConfiguration {

    @XmlElement(name = "log-formatters")
    protected LogFormatters logFormatters;
    @XmlElement(name = "log-destinations")
    protected LogDestinations logDestinations;
    @XmlElement(name = "log-controllers")
    protected LogControllers logControllers;

    /**
     * Gets the value of the logFormatters property.
     * 
     * @return
     *     possible object is
     *     {@link LogFormatters }
     *     
     */
    public LogFormatters getLogFormatters() {
        return logFormatters;
    }

    /**
     * Sets the value of the logFormatters property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogFormatters }
     *     
     */
    public void setLogFormatters(LogFormatters value) {
        this.logFormatters = value;
    }

    /**
     * Gets the value of the logDestinations property.
     * 
     * @return
     *     possible object is
     *     {@link LogDestinations }
     *     
     */
    public LogDestinations getLogDestinations() {
        return logDestinations;
    }

    /**
     * Sets the value of the logDestinations property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogDestinations }
     *     
     */
    public void setLogDestinations(LogDestinations value) {
        this.logDestinations = value;
    }

    /**
     * Gets the value of the logControllers property.
     * 
     * @return
     *     possible object is
     *     {@link LogControllers }
     *     
     */
    public LogControllers getLogControllers() {
        return logControllers;
    }

    /**
     * Sets the value of the logControllers property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogControllers }
     *     
     */
    public void setLogControllers(LogControllers value) {
        this.logControllers = value;
    }

}
