//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:52:46 AM MSK 
//


package logConfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "formatterRefOrAnonymousFormatter",
    "logFilters"
})
@XmlRootElement(name = "log-destination")
public class LogDestination {

    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String name;
    @XmlAttribute(name = "type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "pattern")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pattern;
    @XmlAttribute(name = "effective-severity")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String effectiveSeverity;
    @XmlAttribute(name = "encoding")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String encoding;
    @XmlAttribute(name = "count")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String count;
    @XmlAttribute(name = "limit")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String limit;
    @XmlElements({
        @XmlElement(name = "formatter-ref", type = FormatterRef.class),
        @XmlElement(name = "anonymous-formatter", type = AnonymousFormatter.class)
    })
    protected List<Object> formatterRefOrAnonymousFormatter;
    @XmlElement(name = "log-filters")
    protected LogFilters logFilters;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the pattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPattern(String value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the effectiveSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveSeverity() {
        return effectiveSeverity;
    }

    /**
     * Sets the value of the effectiveSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveSeverity(String value) {
        this.effectiveSeverity = value;
    }

    /**
     * Gets the value of the encoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncoding() {
        return encoding;
    }

    /**
     * Sets the value of the encoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncoding(String value) {
        this.encoding = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCount(String value) {
        this.count = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLimit(String value) {
        this.limit = value;
    }

    /**
     * Gets the value of the formatterRefOrAnonymousFormatter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formatterRefOrAnonymousFormatter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormatterRefOrAnonymousFormatter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormatterRef }
     * {@link AnonymousFormatter }
     * 
     * 
     */
    public List<Object> getFormatterRefOrAnonymousFormatter() {
        if (formatterRefOrAnonymousFormatter == null) {
            formatterRefOrAnonymousFormatter = new ArrayList<Object>();
        }
        return this.formatterRefOrAnonymousFormatter;
    }

    /**
     * Gets the value of the logFilters property.
     * 
     * @return
     *     possible object is
     *     {@link LogFilters }
     *     
     */
    public LogFilters getLogFilters() {
        return logFilters;
    }

    /**
     * Sets the value of the logFilters property.
     * 
     * @param value
     *     allowed object is
     *     {@link LogFilters }
     *     
     */
    public void setLogFilters(LogFilters value) {
        this.logFilters = value;
    }

}
