//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:01:08 PM MSK 
//


package logConfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "logDestination"
})
@XmlRootElement(name = "log-destinations")
public class LogDestinations {

    @XmlElement(name = "log-destination")
    protected List<LogDestination> logDestination;

    /**
     * Gets the value of the logDestination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logDestination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogDestination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LogDestination }
     * 
     * 
     */
    public List<LogDestination> getLogDestination() {
        if (logDestination == null) {
            logDestination = new ArrayList<LogDestination>();
        }
        return this.logDestination;
    }

}
