//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:52:46 AM MSK 
//


package logConfiguration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "logFormatter"
})
@XmlRootElement(name = "log-formatters")
public class LogFormatters {

    @XmlElement(name = "log-formatter")
    protected List<LogFormatter> logFormatter;

    /**
     * Gets the value of the logFormatter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logFormatter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogFormatter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LogFormatter }
     * 
     * 
     */
    public List<LogFormatter> getLogFormatter() {
        if (logFormatter == null) {
            logFormatter = new ArrayList<LogFormatter>();
        }
        return this.logFormatter;
    }

}
