//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:01:08 PM MSK 
//


package logConfiguration;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the logConfiguration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: logConfiguration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AssociatedDestinations }
     * 
     */
    public AssociatedDestinations createAssociatedDestinations() {
        return new AssociatedDestinations();
    }

    /**
     * Create an instance of {@link DestinationRef }
     * 
     */
    public DestinationRef createDestinationRef() {
        return new DestinationRef();
    }

    /**
     * Create an instance of {@link AnonymousDestination }
     * 
     */
    public AnonymousDestination createAnonymousDestination() {
        return new AnonymousDestination();
    }

    /**
     * Create an instance of {@link LogFilter }
     * 
     */
    public LogFilter createLogFilter() {
        return new LogFilter();
    }

    /**
     * Create an instance of {@link FormatterRef }
     * 
     */
    public FormatterRef createFormatterRef() {
        return new FormatterRef();
    }

    /**
     * Create an instance of {@link LogController }
     * 
     */
    public LogController createLogController() {
        return new LogController();
    }

    /**
     * Create an instance of {@link RelativeSeverity }
     * 
     */
    public RelativeSeverity createRelativeSeverity() {
        return new RelativeSeverity();
    }

    /**
     * Create an instance of {@link LogFilters }
     * 
     */
    public LogFilters createLogFilters() {
        return new LogFilters();
    }

    /**
     * Create an instance of {@link LogConfiguration }
     * 
     */
    public LogConfiguration createLogConfiguration() {
        return new LogConfiguration();
    }

    /**
     * Create an instance of {@link LogFormatters }
     * 
     */
    public LogFormatters createLogFormatters() {
        return new LogFormatters();
    }

    /**
     * Create an instance of {@link LogDestinations }
     * 
     */
    public LogDestinations createLogDestinations() {
        return new LogDestinations();
    }

    /**
     * Create an instance of {@link LogControllers }
     * 
     */
    public LogControllers createLogControllers() {
        return new LogControllers();
    }

    /**
     * Create an instance of {@link LogFormatter }
     * 
     */
    public LogFormatter createLogFormatter() {
        return new LogFormatter();
    }

    /**
     * Create an instance of {@link LogDestination }
     * 
     */
    public LogDestination createLogDestination() {
        return new LogDestination();
    }

    /**
     * Create an instance of {@link AnonymousFormatter }
     * 
     */
    public AnonymousFormatter createAnonymousFormatter() {
        return new AnonymousFormatter();
    }

}
