//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:47:05 AM MSK 
//


package applicationj2eeengine;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reference" type="{}referenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="library-loader" type="{}libraryLoaderType" minOccurs="0"/>
 *         &lt;element ref="{}classpath" minOccurs="0"/>
 *         &lt;element ref="{}provider-name" minOccurs="0"/>
 *         &lt;element name="modules-additional" type="{}modules-additionalType" minOccurs="0"/>
 *         &lt;element name="fail-over-enable" type="{}fail-over-enableType" minOccurs="0"/>
 *         &lt;element name="start-up" type="{}start-upType" minOccurs="0"/>
 *         &lt;element ref="{}java-version" minOccurs="0"/>
 *         &lt;element name="exclude-default-reference" type="{}excludeDefaultReferenceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reference",
    "libraryLoader",
    "classpath",
    "providerName",
    "modulesAdditional",
    "failOverEnable",
    "startUp",
    "javaVersion",
    "excludeDefaultReference"
})
@XmlRootElement(name = "application-j2ee-engine")
public class ApplicationJ2EeEngine {

    protected List<ReferenceType> reference;
    @XmlElement(name = "library-loader")
    protected LibraryLoaderType libraryLoader;
    protected String classpath;
    @XmlElement(name = "provider-name")
    protected String providerName;
    @XmlElement(name = "modules-additional")
    protected ModulesAdditionalType modulesAdditional;
    @XmlElement(name = "fail-over-enable")
    protected FailOverEnableType failOverEnable;
    @XmlElement(name = "start-up")
    protected StartUpType startUp;
    @XmlElement(name = "java-version")
    protected String javaVersion;
    @XmlElement(name = "exclude-default-reference")
    protected List<ExcludeDefaultReferenceType> excludeDefaultReference;

    /**
     * Gets the value of the reference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceType }
     * 
     * 
     */
    public List<ReferenceType> getReference() {
        if (reference == null) {
            reference = new ArrayList<ReferenceType>();
        }
        return this.reference;
    }

    /**
     * Gets the value of the libraryLoader property.
     * 
     * @return
     *     possible object is
     *     {@link LibraryLoaderType }
     *     
     */
    public LibraryLoaderType getLibraryLoader() {
        return libraryLoader;
    }

    /**
     * Sets the value of the libraryLoader property.
     * 
     * @param value
     *     allowed object is
     *     {@link LibraryLoaderType }
     *     
     */
    public void setLibraryLoader(LibraryLoaderType value) {
        this.libraryLoader = value;
    }

    /**
     * Gets the value of the classpath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClasspath() {
        return classpath;
    }

    /**
     * Sets the value of the classpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClasspath(String value) {
        this.classpath = value;
    }

    /**
     * Gets the value of the providerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderName() {
        return providerName;
    }

    /**
     * Sets the value of the providerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderName(String value) {
        this.providerName = value;
    }

    /**
     * Gets the value of the modulesAdditional property.
     * 
     * @return
     *     possible object is
     *     {@link ModulesAdditionalType }
     *     
     */
    public ModulesAdditionalType getModulesAdditional() {
        return modulesAdditional;
    }

    /**
     * Sets the value of the modulesAdditional property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModulesAdditionalType }
     *     
     */
    public void setModulesAdditional(ModulesAdditionalType value) {
        this.modulesAdditional = value;
    }

    /**
     * Gets the value of the failOverEnable property.
     * 
     * @return
     *     possible object is
     *     {@link FailOverEnableType }
     *     
     */
    public FailOverEnableType getFailOverEnable() {
        return failOverEnable;
    }

    /**
     * Sets the value of the failOverEnable property.
     * 
     * @param value
     *     allowed object is
     *     {@link FailOverEnableType }
     *     
     */
    public void setFailOverEnable(FailOverEnableType value) {
        this.failOverEnable = value;
    }

    /**
     * Gets the value of the startUp property.
     * 
     * @return
     *     possible object is
     *     {@link StartUpType }
     *     
     */
    public StartUpType getStartUp() {
        return startUp;
    }

    /**
     * Sets the value of the startUp property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartUpType }
     *     
     */
    public void setStartUp(StartUpType value) {
        this.startUp = value;
    }

    /**
     * Gets the value of the javaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJavaVersion() {
        return javaVersion;
    }

    /**
     * Sets the value of the javaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJavaVersion(String value) {
        this.javaVersion = value;
    }

    /**
     * Gets the value of the excludeDefaultReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the excludeDefaultReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExcludeDefaultReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExcludeDefaultReferenceType }
     * 
     * 
     */
    public List<ExcludeDefaultReferenceType> getExcludeDefaultReference() {
        if (excludeDefaultReference == null) {
            excludeDefaultReference = new ArrayList<ExcludeDefaultReferenceType>();
        }
        return this.excludeDefaultReference;
    }

}
