//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:47:05 AM MSK 
//


package applicationj2eeengine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for excludeDefaultReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="excludeDefaultReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reference-target" type="{}reference-targetType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "excludeDefaultReferenceType", propOrder = {
    "referenceTarget"
})
public class ExcludeDefaultReferenceType {

    @XmlElement(name = "reference-target", required = true)
    protected ReferenceTargetType referenceTarget;

    /**
     * Gets the value of the referenceTarget property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceTargetType }
     *     
     */
    public ReferenceTargetType getReferenceTarget() {
        return referenceTarget;
    }

    /**
     * Sets the value of the referenceTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceTargetType }
     *     
     */
    public void setReferenceTarget(ReferenceTargetType value) {
        this.referenceTarget = value;
    }

}
