//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:47:05 AM MSK 
//


package applicationj2eeengine;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the applicationj2eeengine package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ProviderName_QNAME = new QName("", "provider-name");
    private final static QName _Classpath_QNAME = new QName("", "classpath");
    private final static QName _JavaVersion_QNAME = new QName("", "java-version");
    private final static QName _ContainerType_QNAME = new QName("", "container-type");
    private final static QName _EntryName_QNAME = new QName("", "entry-name");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: applicationj2eeengine
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplicationJ2EeEngine }
     * 
     */
    public ApplicationJ2EeEngine createApplicationJ2EeEngine() {
        return new ApplicationJ2EeEngine();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link LibraryLoaderType }
     * 
     */
    public LibraryLoaderType createLibraryLoaderType() {
        return new LibraryLoaderType();
    }

    /**
     * Create an instance of {@link ModulesAdditionalType }
     * 
     */
    public ModulesAdditionalType createModulesAdditionalType() {
        return new ModulesAdditionalType();
    }

    /**
     * Create an instance of {@link FailOverEnableType }
     * 
     */
    public FailOverEnableType createFailOverEnableType() {
        return new FailOverEnableType();
    }

    /**
     * Create an instance of {@link StartUpType }
     * 
     */
    public StartUpType createStartUpType() {
        return new StartUpType();
    }

    /**
     * Create an instance of {@link ExcludeDefaultReferenceType }
     * 
     */
    public ExcludeDefaultReferenceType createExcludeDefaultReferenceType() {
        return new ExcludeDefaultReferenceType();
    }

    /**
     * Create an instance of {@link ModuleType }
     * 
     */
    public ModuleType createModuleType() {
        return new ModuleType();
    }

    /**
     * Create an instance of {@link LibLoaderReferenceType }
     * 
     */
    public LibLoaderReferenceType createLibLoaderReferenceType() {
        return new LibLoaderReferenceType();
    }

    /**
     * Create an instance of {@link LibLoaderReferenceTargetType }
     * 
     */
    public LibLoaderReferenceTargetType createLibLoaderReferenceTargetType() {
        return new LibLoaderReferenceTargetType();
    }

    /**
     * Create an instance of {@link ReferenceTargetType }
     * 
     */
    public ReferenceTargetType createReferenceTargetType() {
        return new ReferenceTargetType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "provider-name")
    public JAXBElement<String> createProviderName(String value) {
        return new JAXBElement<String>(_ProviderName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "classpath")
    public JAXBElement<String> createClasspath(String value) {
        return new JAXBElement<String>(_Classpath_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "java-version")
    public JAXBElement<String> createJavaVersion(String value) {
        return new JAXBElement<String>(_JavaVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "container-type")
    public JAXBElement<String> createContainerType(String value) {
        return new JAXBElement<String>(_ContainerType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "entry-name")
    public JAXBElement<String> createEntryName(String value) {
        return new JAXBElement<String>(_EntryName_QNAME, String.class, null, value);
    }

}
