//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 07:47:05 AM MSK 
//


package applicationj2eeengine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for referenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="referenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="reference-target" type="{}reference-targetType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="reference-type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="hard"/>
 *             &lt;enumeration value="weak"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="prepend" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "referenceType", propOrder = {
    "referenceTarget"
})
public class ReferenceType {

    @XmlElement(name = "reference-target", required = true)
    protected ReferenceTargetType referenceTarget;
    @XmlAttribute(name = "reference-type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String referenceType;
    @XmlAttribute(name = "prepend")
    protected Boolean prepend;

    /**
     * Gets the value of the referenceTarget property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceTargetType }
     *     
     */
    public ReferenceTargetType getReferenceTarget() {
        return referenceTarget;
    }

    /**
     * Sets the value of the referenceTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceTargetType }
     *     
     */
    public void setReferenceTarget(ReferenceTargetType value) {
        this.referenceTarget = value;
    }

    /**
     * Gets the value of the referenceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceType() {
        return referenceType;
    }

    /**
     * Sets the value of the referenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceType(String value) {
        this.referenceType = value;
    }

    /**
     * Gets the value of the prepend property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPrepend() {
        if (prepend == null) {
            return false;
        } else {
            return prepend;
        }
    }

    /**
     * Sets the value of the prepend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrepend(Boolean value) {
        this.prepend = value;
    }

}
