//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:39 AM MSK 
//


package connector15;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 
 * 	The authentication-mechanismType specifies an authentication
 * 	mechanism supported by the resource adapter. Note that this
 * 	support is for the resource adapter and not for the
 * 	underlying EIS instance. The optional description specifies
 * 	any resource adapter specific requirement for the support of
 * 	security contract and authentication mechanism.
 * 
 * 	Note that BasicPassword mechanism type should support the
 * 	javax.resource.spi.security.PasswordCredential interface.
 * 	The Kerbv5 mechanism type should support the
 * 	org.ietf.jgss.GSSCredential interface or the deprecated
 * 	javax.resource.spi.security.GenericCredential interface.
 * 
 *       
 * 
 * <p>Java class for authentication-mechanismType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authentication-mechanismType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://java.sun.com/xml/ns/j2ee}descriptionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="authentication-mechanism-type" type="{http://java.sun.com/xml/ns/j2ee}xsdStringType"/>
 *         &lt;element name="credential-interface" type="{http://java.sun.com/xml/ns/j2ee}credential-interfaceType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authentication-mechanismType", propOrder = {
    "description",
    "authenticationMechanismType",
    "credentialInterface"
})
public class AuthenticationMechanismType {

    protected List<DescriptionType> description;
    @XmlElement(name = "authentication-mechanism-type", required = true)
    protected XsdStringType authenticationMechanismType;
    @XmlElement(name = "credential-interface", required = true)
    protected CredentialInterfaceType credentialInterface;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the authenticationMechanismType property.
     * 
     * @return
     *     possible object is
     *     {@link XsdStringType }
     *     
     */
    public XsdStringType getAuthenticationMechanismType() {
        return authenticationMechanismType;
    }

    /**
     * Sets the value of the authenticationMechanismType property.
     * 
     * @param value
     *     allowed object is
     *     {@link XsdStringType }
     *     
     */
    public void setAuthenticationMechanismType(XsdStringType value) {
        this.authenticationMechanismType = value;
    }

    /**
     * Gets the value of the credentialInterface property.
     * 
     * @return
     *     possible object is
     *     {@link CredentialInterfaceType }
     *     
     */
    public CredentialInterfaceType getCredentialInterface() {
        return credentialInterface;
    }

    /**
     * Sets the value of the credentialInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredentialInterfaceType }
     *     
     */
    public void setCredentialInterface(CredentialInterfaceType value) {
        this.credentialInterface = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
