//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:39 AM MSK 
//


package connector15;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 
 * 	The connection-definitionType defines a set of connection
 * 	interfaces and classes pertaining to a particular connection
 * 	type. This also includes configurable properties for
 * 	ManagedConnectionFactory instances that may be produced out
 * 	of this set.
 * 
 *       
 * 
 * <p>Java class for connection-definitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="connection-definitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="managedconnectionfactory-class" type="{http://java.sun.com/xml/ns/j2ee}fully-qualified-classType"/>
 *         &lt;element name="config-property" type="{http://java.sun.com/xml/ns/j2ee}config-propertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="connectionfactory-interface" type="{http://java.sun.com/xml/ns/j2ee}fully-qualified-classType"/>
 *         &lt;element name="connectionfactory-impl-class" type="{http://java.sun.com/xml/ns/j2ee}fully-qualified-classType"/>
 *         &lt;element name="connection-interface" type="{http://java.sun.com/xml/ns/j2ee}fully-qualified-classType"/>
 *         &lt;element name="connection-impl-class" type="{http://java.sun.com/xml/ns/j2ee}fully-qualified-classType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "connection-definitionType", propOrder = {
    "managedconnectionfactoryClass",
    "configProperty",
    "connectionfactoryInterface",
    "connectionfactoryImplClass",
    "connectionInterface",
    "connectionImplClass"
})
public class ConnectionDefinitionType {

    @XmlElement(name = "managedconnectionfactory-class", required = true)
    protected FullyQualifiedClassType managedconnectionfactoryClass;
    @XmlElement(name = "config-property")
    protected List<ConfigPropertyType> configProperty;
    @XmlElement(name = "connectionfactory-interface", required = true)
    protected FullyQualifiedClassType connectionfactoryInterface;
    @XmlElement(name = "connectionfactory-impl-class", required = true)
    protected FullyQualifiedClassType connectionfactoryImplClass;
    @XmlElement(name = "connection-interface", required = true)
    protected FullyQualifiedClassType connectionInterface;
    @XmlElement(name = "connection-impl-class", required = true)
    protected FullyQualifiedClassType connectionImplClass;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the managedconnectionfactoryClass property.
     * 
     * @return
     *     possible object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public FullyQualifiedClassType getManagedconnectionfactoryClass() {
        return managedconnectionfactoryClass;
    }

    /**
     * Sets the value of the managedconnectionfactoryClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public void setManagedconnectionfactoryClass(FullyQualifiedClassType value) {
        this.managedconnectionfactoryClass = value;
    }

    /**
     * Gets the value of the configProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfigProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigPropertyType }
     * 
     * 
     */
    public List<ConfigPropertyType> getConfigProperty() {
        if (configProperty == null) {
            configProperty = new ArrayList<ConfigPropertyType>();
        }
        return this.configProperty;
    }

    /**
     * Gets the value of the connectionfactoryInterface property.
     * 
     * @return
     *     possible object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public FullyQualifiedClassType getConnectionfactoryInterface() {
        return connectionfactoryInterface;
    }

    /**
     * Sets the value of the connectionfactoryInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public void setConnectionfactoryInterface(FullyQualifiedClassType value) {
        this.connectionfactoryInterface = value;
    }

    /**
     * Gets the value of the connectionfactoryImplClass property.
     * 
     * @return
     *     possible object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public FullyQualifiedClassType getConnectionfactoryImplClass() {
        return connectionfactoryImplClass;
    }

    /**
     * Sets the value of the connectionfactoryImplClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public void setConnectionfactoryImplClass(FullyQualifiedClassType value) {
        this.connectionfactoryImplClass = value;
    }

    /**
     * Gets the value of the connectionInterface property.
     * 
     * @return
     *     possible object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public FullyQualifiedClassType getConnectionInterface() {
        return connectionInterface;
    }

    /**
     * Sets the value of the connectionInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public void setConnectionInterface(FullyQualifiedClassType value) {
        this.connectionInterface = value;
    }

    /**
     * Gets the value of the connectionImplClass property.
     * 
     * @return
     *     possible object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public FullyQualifiedClassType getConnectionImplClass() {
        return connectionImplClass;
    }

    /**
     * Sets the value of the connectionImplClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public void setConnectionImplClass(FullyQualifiedClassType value) {
        this.connectionImplClass = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
