//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:39 AM MSK 
//


package connector15;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 
 * 	The messagelistenerType specifies information about a
 * 	specific message listener supported by the messaging
 * 	resource adapter. It contains information on the Java type
 * 	of the message listener interface and an activation
 * 	specification.
 * 
 *       
 * 
 * <p>Java class for messagelistenerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="messagelistenerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messagelistener-type" type="{http://java.sun.com/xml/ns/j2ee}fully-qualified-classType"/>
 *         &lt;element name="activationspec" type="{http://java.sun.com/xml/ns/j2ee}activationspecType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "messagelistenerType", propOrder = {
    "messagelistenerType",
    "activationspec"
})
public class MessagelistenerType {

    @XmlElement(name = "messagelistener-type", required = true)
    protected FullyQualifiedClassType messagelistenerType;
    @XmlElement(required = true)
    protected ActivationspecType activationspec;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the messagelistenerType property.
     * 
     * @return
     *     possible object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public FullyQualifiedClassType getMessagelistenerType() {
        return messagelistenerType;
    }

    /**
     * Sets the value of the messagelistenerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public void setMessagelistenerType(FullyQualifiedClassType value) {
        this.messagelistenerType = value;
    }

    /**
     * Gets the value of the activationspec property.
     * 
     * @return
     *     possible object is
     *     {@link ActivationspecType }
     *     
     */
    public ActivationspecType getActivationspec() {
        return activationspec;
    }

    /**
     * Sets the value of the activationspec property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActivationspecType }
     *     
     */
    public void setActivationspec(ActivationspecType value) {
        this.activationspec = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
