//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:39 AM MSK 
//


package connector15;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 
 * 	The outbound-resourceadapterType specifies information about
 * 	an outbound resource adapter. The information includes fully
 * 	qualified names of classes/interfaces required as part of
 * 	the connector architecture specified contracts for
 * 	connection management, level of transaction support
 * 	provided, one or more authentication mechanisms supported
 * 	and additional required security permissions.
 * 
 * 	If there is no authentication-mechanism specified as part of
 * 	resource adapter element then the resource adapter does not
 * 	support any standard security authentication mechanisms as
 * 	part of security contract. The application server ignores
 * 	the security part of the system contracts in this case.
 * 
 *       
 * 
 * <p>Java class for outbound-resourceadapterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="outbound-resourceadapterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connection-definition" type="{http://java.sun.com/xml/ns/j2ee}connection-definitionType" maxOccurs="unbounded"/>
 *         &lt;element name="transaction-support" type="{http://java.sun.com/xml/ns/j2ee}transaction-supportType"/>
 *         &lt;element name="authentication-mechanism" type="{http://java.sun.com/xml/ns/j2ee}authentication-mechanismType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reauthentication-support" type="{http://java.sun.com/xml/ns/j2ee}true-falseType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "outbound-resourceadapterType", propOrder = {
    "connectionDefinition",
    "transactionSupport",
    "authenticationMechanism",
    "reauthenticationSupport"
})
public class OutboundResourceadapterType {

    @XmlElement(name = "connection-definition", required = true)
    protected List<ConnectionDefinitionType> connectionDefinition;
    @XmlElement(name = "transaction-support", required = true)
    protected TransactionSupportType transactionSupport;
    @XmlElement(name = "authentication-mechanism")
    protected List<AuthenticationMechanismType> authenticationMechanism;
    @XmlElement(name = "reauthentication-support", required = true)
    protected TrueFalseType reauthenticationSupport;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the connectionDefinition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connectionDefinition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectionDefinition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConnectionDefinitionType }
     * 
     * 
     */
    public List<ConnectionDefinitionType> getConnectionDefinition() {
        if (connectionDefinition == null) {
            connectionDefinition = new ArrayList<ConnectionDefinitionType>();
        }
        return this.connectionDefinition;
    }

    /**
     * Gets the value of the transactionSupport property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionSupportType }
     *     
     */
    public TransactionSupportType getTransactionSupport() {
        return transactionSupport;
    }

    /**
     * Sets the value of the transactionSupport property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionSupportType }
     *     
     */
    public void setTransactionSupport(TransactionSupportType value) {
        this.transactionSupport = value;
    }

    /**
     * Gets the value of the authenticationMechanism property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authenticationMechanism property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthenticationMechanism().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AuthenticationMechanismType }
     * 
     * 
     */
    public List<AuthenticationMechanismType> getAuthenticationMechanism() {
        if (authenticationMechanism == null) {
            authenticationMechanism = new ArrayList<AuthenticationMechanismType>();
        }
        return this.authenticationMechanism;
    }

    /**
     * Gets the value of the reauthenticationSupport property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getReauthenticationSupport() {
        return reauthenticationSupport;
    }

    /**
     * Sets the value of the reauthenticationSupport property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setReauthenticationSupport(TrueFalseType value) {
        this.reauthenticationSupport = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
