//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:39 AM MSK 
//


package connector15;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 
 * 	The resourceadapterType specifies information about the
 * 	resource adapter. The information includes fully qualified
 * 	resource adapter Java class name, configuration properties,
 * 	information specific to the implementation of the resource
 * 	adapter library as specified through the
 * 	outbound-resourceadapter and inbound-resourceadapter
 * 	elements, and an optional set of administered objects.
 * 
 *       
 * 
 * <p>Java class for resourceadapterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceadapterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resourceadapter-class" type="{http://java.sun.com/xml/ns/j2ee}fully-qualified-classType" minOccurs="0"/>
 *         &lt;element name="config-property" type="{http://java.sun.com/xml/ns/j2ee}config-propertyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="outbound-resourceadapter" type="{http://java.sun.com/xml/ns/j2ee}outbound-resourceadapterType" minOccurs="0"/>
 *         &lt;element name="inbound-resourceadapter" type="{http://java.sun.com/xml/ns/j2ee}inbound-resourceadapterType" minOccurs="0"/>
 *         &lt;element name="adminobject" type="{http://java.sun.com/xml/ns/j2ee}adminobjectType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="security-permission" type="{http://java.sun.com/xml/ns/j2ee}security-permissionType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceadapterType", propOrder = {
    "resourceadapterClass",
    "configProperty",
    "outboundResourceadapter",
    "inboundResourceadapter",
    "adminobject",
    "securityPermission"
})
public class ResourceadapterType {

    @XmlElement(name = "resourceadapter-class")
    protected FullyQualifiedClassType resourceadapterClass;
    @XmlElement(name = "config-property")
    protected List<ConfigPropertyType> configProperty;
    @XmlElement(name = "outbound-resourceadapter")
    protected OutboundResourceadapterType outboundResourceadapter;
    @XmlElement(name = "inbound-resourceadapter")
    protected InboundResourceadapterType inboundResourceadapter;
    protected List<AdminobjectType> adminobject;
    @XmlElement(name = "security-permission")
    protected List<SecurityPermissionType> securityPermission;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the resourceadapterClass property.
     * 
     * @return
     *     possible object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public FullyQualifiedClassType getResourceadapterClass() {
        return resourceadapterClass;
    }

    /**
     * Sets the value of the resourceadapterClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link FullyQualifiedClassType }
     *     
     */
    public void setResourceadapterClass(FullyQualifiedClassType value) {
        this.resourceadapterClass = value;
    }

    /**
     * Gets the value of the configProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the configProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConfigProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConfigPropertyType }
     * 
     * 
     */
    public List<ConfigPropertyType> getConfigProperty() {
        if (configProperty == null) {
            configProperty = new ArrayList<ConfigPropertyType>();
        }
        return this.configProperty;
    }

    /**
     * Gets the value of the outboundResourceadapter property.
     * 
     * @return
     *     possible object is
     *     {@link OutboundResourceadapterType }
     *     
     */
    public OutboundResourceadapterType getOutboundResourceadapter() {
        return outboundResourceadapter;
    }

    /**
     * Sets the value of the outboundResourceadapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutboundResourceadapterType }
     *     
     */
    public void setOutboundResourceadapter(OutboundResourceadapterType value) {
        this.outboundResourceadapter = value;
    }

    /**
     * Gets the value of the inboundResourceadapter property.
     * 
     * @return
     *     possible object is
     *     {@link InboundResourceadapterType }
     *     
     */
    public InboundResourceadapterType getInboundResourceadapter() {
        return inboundResourceadapter;
    }

    /**
     * Sets the value of the inboundResourceadapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundResourceadapterType }
     *     
     */
    public void setInboundResourceadapter(InboundResourceadapterType value) {
        this.inboundResourceadapter = value;
    }

    /**
     * Gets the value of the adminobject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adminobject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdminobject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdminobjectType }
     * 
     * 
     */
    public List<AdminobjectType> getAdminobject() {
        if (adminobject == null) {
            adminobject = new ArrayList<AdminobjectType>();
        }
        return this.adminobject;
    }

    /**
     * Gets the value of the securityPermission property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityPermission property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurityPermission().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecurityPermissionType }
     * 
     * 
     */
    public List<SecurityPermissionType> getSecurityPermission() {
        if (securityPermission == null) {
            securityPermission = new ArrayList<SecurityPermissionType>();
        }
        return this.securityPermission;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
