<?xml version="1.0" encoding="UTF-8"?>

<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output method="xml" indent="yes"/>

<xsl:template match="connector-j2ee-engine">
<connector xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="connector-j2ee-engine.xsd">
	<description>Generated by backward compatibility tool</description>
	<resourceadapter>
		<outbound-resourceadapter>
			<connection-definition>
				<connectionfactory-interface><xsl:value-of select="./connectionfactory-interface"/></connectionfactory-interface>
				<xsl:if  test="count(./jndi-name)=1">
				<jndi-name><xsl:value-of select="./jndi-name"/></jndi-name>
				</xsl:if>
				<xsl:for-each select="./alias">
				<alias><xsl:value-of select="."/></alias>
				</xsl:for-each>
				<xsl:if  test="count(./destination-name)=1">
					<destination-name><xsl:value-of select="./destination-name"/></destination-name>
				</xsl:if>
				<xsl:if  test="count(./authentication-mechanism-type)=1">
				<authentication-mechanism-type><xsl:value-of select="./authentication-mechanism-type"/></authentication-mechanism-type>
				</xsl:if>
				<xsl:if  test="count(./authentication-type)=1">
				<authentication-type><xsl:value-of select="./authentication-type"/></authentication-type>
				</xsl:if>
				<xsl:if  test="count(./user-store)=1">
				<user-store><xsl:value-of select="./user-store"/></user-store>
				</xsl:if>
				<xsl:apply-templates select="identity-subject"/>
				<xsl:if  test="count(./pool-params)=1">
				<pool-params>
					<max-connections-number><xsl:value-of select="./pool-params/max-connections-number"/></max-connections-number>
					<xsl:if  test="count(./pool-params/max-time-to-wait-connection)=1">
					<max-time-to-wait-connection><xsl:value-of select="./pool-params/max-time-to-wait-connection"/></max-time-to-wait-connection>
					</xsl:if>
					<xsl:if  test="count(./pool-params/expiration-control)=1">
					<expiration-control>
						<connection-lifetime><xsl:value-of select="./pool-params/expiration-control/connection-lifetime"/></connection-lifetime> 
						<run-cleanup-thread-interval><xsl:value-of select="./pool-params/expiration-control/run-cleanup-thread"/></run-cleanup-thread-interval>
					</expiration-control>
					</xsl:if>
				</pool-params>
				</xsl:if>
			</connection-definition>
		</outbound-resourceadapter>
		<xsl:if  test="count(./loader-references)=1">
			<xsl:if  test="count(./loader-references/loader-name)>0">
				<loader-references>
					<xsl:for-each select="./loader-references/loader-name">							
					<xsl:element name = "loader-name">   
						<xsl:if  test="count(./@strength)>0">				
						<xsl:attribute name = "strength"> <xsl:value-of select="@strength"/></xsl:attribute>
						</xsl:if>						
  						<xsl:value-of select="."/>
					</xsl:element >				
					</xsl:for-each>
				</loader-references>
			</xsl:if>							
		</xsl:if>
    <xsl:if test="./properties/property">
      <extended-properties>
      <xsl:apply-templates select="./properties/property"/>
      </extended-properties>
    </xsl:if>
	</resourceadapter>
</connector>
</xsl:template>


<xsl:template match="identity-subject">
	<identity-subject>
		<xsl:if  test="count(./caller-principal)=1">
 		<caller-principal>
			<xsl:for-each select="./caller-principal/group-name">
			<group-name><xsl:value-of select="."/></group-name>
			</xsl:for-each>
			<xsl:for-each select="./caller-principal/user-name">
			<user-name><xsl:value-of select="."/></user-name>
			</xsl:for-each>
		</caller-principal>
		</xsl:if>
		<resource-principal>
			<user-name><xsl:value-of select="./resource-principal/user-name"/></user-name>
			<user-password><xsl:value-of select="./resource-principal/user-password"/></user-password>
		</resource-principal>
	</identity-subject>
</xsl:template>

<xsl:template match="property">
	<property>
	  <property-name><xsl:value-of select="./property-name"/></property-name>
	  <property-value><xsl:value-of select="./property-value"/></property-value>
	</property>
</xsl:template>

</xsl:transform>
