//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:40 AM MSK 
//


package connectorj2eeengine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clonningType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="clonningType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="template-app-name" type="{}xsdStringType"/>
 *         &lt;element name="template-ra-name" type="{}xsdStringType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clonningType", namespace = "", propOrder = {
    "templateAppName",
    "templateRaName"
})
public class ClonningType {

    @XmlElement(name = "template-app-name", required = true)
    protected XsdStringType2 templateAppName;
    @XmlElement(name = "template-ra-name", required = true)
    protected XsdStringType2 templateRaName;

    /**
     * Gets the value of the templateAppName property.
     * 
     * @return
     *     possible object is
     *     {@link XsdStringType2 }
     *     
     */
    public XsdStringType2 getTemplateAppName() {
        return templateAppName;
    }

    /**
     * Sets the value of the templateAppName property.
     * 
     * @param value
     *     allowed object is
     *     {@link XsdStringType2 }
     *     
     */
    public void setTemplateAppName(XsdStringType2 value) {
        this.templateAppName = value;
    }

    /**
     * Gets the value of the templateRaName property.
     * 
     * @return
     *     possible object is
     *     {@link XsdStringType2 }
     *     
     */
    public XsdStringType2 getTemplateRaName() {
        return templateRaName;
    }

    /**
     * Sets the value of the templateRaName property.
     * 
     * @param value
     *     allowed object is
     *     {@link XsdStringType2 }
     *     
     */
    public void setTemplateRaName(XsdStringType2 value) {
        this.templateRaName = value;
    }

}
