//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:40 AM MSK 
//


package connectorj2eeengine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			        The connectorType defines a resource adapter.
 * 		      
 * 
 * <p>Java class for connectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="connectorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="resourceadapter" type="{}resourceadapterType"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="template" type="{http://java.sun.com/xml/ns/j2ee}emptyType"/>
 *           &lt;element name="clonning" type="{}clonningType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "connectorType", namespace = "", propOrder = {
    "description",
    "resourceadapter",
    "template",
    "clonning"
})
public class ConnectorType {

    protected java.lang.String description;
    @XmlElement(required = true)
    protected ResourceadapterType resourceadapter;
    protected EmptyType template;
    protected ClonningType clonning;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDescription(java.lang.String value) {
        this.description = value;
    }

    /**
     * Gets the value of the resourceadapter property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceadapterType }
     *     
     */
    public ResourceadapterType getResourceadapter() {
        return resourceadapter;
    }

    /**
     * Sets the value of the resourceadapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceadapterType }
     *     
     */
    public void setResourceadapter(ResourceadapterType value) {
        this.resourceadapter = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link EmptyType }
     *     
     */
    public EmptyType getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmptyType }
     *     
     */
    public void setTemplate(EmptyType value) {
        this.template = value;
    }

    /**
     * Gets the value of the clonning property.
     * 
     * @return
     *     possible object is
     *     {@link ClonningType }
     *     
     */
    public ClonningType getClonning() {
        return clonning;
    }

    /**
     * Sets the value of the clonning property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClonningType }
     *     
     */
    public void setClonning(ClonningType value) {
        this.clonning = value;
    }

}
