//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:40 AM MSK 
//


package connectorj2eeengine;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for connection-definitionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="connection-definitionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connectionfactory-interface" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="jndi-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="alias" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="destination-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="authentication-mechanism-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="authentication-type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="user-store" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="identity-subject" type="{}identity-subjectType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pool-params" type="{}pool-paramsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "connection-definitionType", namespace = "", propOrder = {
    "connectionfactoryInterface",
    "jndiName",
    "alias",
    "destinationName",
    "authenticationMechanismType",
    "authenticationType",
    "userStore",
    "identitySubject",
    "poolParams"
})
public class ConnectionDefinitionType {

    @XmlElement(name = "connectionfactory-interface", required = true)
    protected java.lang.String connectionfactoryInterface;
    @XmlElement(name = "jndi-name")
    protected java.lang.String jndiName;
    protected List<java.lang.String> alias;
    @XmlElement(name = "destination-name")
    protected java.lang.String destinationName;
    @XmlElement(name = "authentication-mechanism-type")
    protected java.lang.String authenticationMechanismType;
    @XmlElement(name = "authentication-type")
    protected java.lang.String authenticationType;
    @XmlElement(name = "user-store")
    protected java.lang.String userStore;
    @XmlElement(name = "identity-subject")
    protected List<IdentitySubjectType> identitySubject;
    @XmlElement(name = "pool-params")
    protected PoolParamsType poolParams;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected java.lang.String id;

    /**
     * Gets the value of the connectionfactoryInterface property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getConnectionfactoryInterface() {
        return connectionfactoryInterface;
    }

    /**
     * Sets the value of the connectionfactoryInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setConnectionfactoryInterface(java.lang.String value) {
        this.connectionfactoryInterface = value;
    }

    /**
     * Gets the value of the jndiName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getJndiName() {
        return jndiName;
    }

    /**
     * Sets the value of the jndiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setJndiName(java.lang.String value) {
        this.jndiName = value;
    }

    /**
     * Gets the value of the alias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link java.lang.String }
     * 
     * 
     */
    public List<java.lang.String> getAlias() {
        if (alias == null) {
            alias = new ArrayList<java.lang.String>();
        }
        return this.alias;
    }

    /**
     * Gets the value of the destinationName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDestinationName() {
        return destinationName;
    }

    /**
     * Sets the value of the destinationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDestinationName(java.lang.String value) {
        this.destinationName = value;
    }

    /**
     * Gets the value of the authenticationMechanismType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAuthenticationMechanismType() {
        return authenticationMechanismType;
    }

    /**
     * Sets the value of the authenticationMechanismType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAuthenticationMechanismType(java.lang.String value) {
        this.authenticationMechanismType = value;
    }

    /**
     * Gets the value of the authenticationType property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getAuthenticationType() {
        return authenticationType;
    }

    /**
     * Sets the value of the authenticationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setAuthenticationType(java.lang.String value) {
        this.authenticationType = value;
    }

    /**
     * Gets the value of the userStore property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getUserStore() {
        return userStore;
    }

    /**
     * Sets the value of the userStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setUserStore(java.lang.String value) {
        this.userStore = value;
    }

    /**
     * Gets the value of the identitySubject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identitySubject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentitySubject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentitySubjectType }
     * 
     * 
     */
    public List<IdentitySubjectType> getIdentitySubject() {
        if (identitySubject == null) {
            identitySubject = new ArrayList<IdentitySubjectType>();
        }
        return this.identitySubject;
    }

    /**
     * Gets the value of the poolParams property.
     * 
     * @return
     *     possible object is
     *     {@link PoolParamsType }
     *     
     */
    public PoolParamsType getPoolParams() {
        return poolParams;
    }

    /**
     * Sets the value of the poolParams property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoolParamsType }
     *     
     */
    public void setPoolParams(PoolParamsType value) {
        this.poolParams = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

}
