//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:40 AM MSK 
//


package connectorj2eeengine;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for expiration-controlType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="expiration-controlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="connection-lifetime" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="run-cleanup-thread-interval" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "expiration-controlType", namespace = "", propOrder = {
    "connectionLifetime",
    "runCleanupThreadInterval"
})
public class ExpirationControlType {

    @XmlElement(name = "connection-lifetime", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger connectionLifetime;
    @XmlElement(name = "run-cleanup-thread-interval", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger runCleanupThreadInterval;

    /**
     * Gets the value of the connectionLifetime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConnectionLifetime() {
        return connectionLifetime;
    }

    /**
     * Sets the value of the connectionLifetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConnectionLifetime(BigInteger value) {
        this.connectionLifetime = value;
    }

    /**
     * Gets the value of the runCleanupThreadInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRunCleanupThreadInterval() {
        return runCleanupThreadInterval;
    }

    /**
     * Sets the value of the runCleanupThreadInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRunCleanupThreadInterval(BigInteger value) {
        this.runCleanupThreadInterval = value;
    }

}
