//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:40 AM MSK 
//


package connectorj2eeengine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for identity-subjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identity-subjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="caller-principal" type="{}caller-principalType" minOccurs="0"/>
 *         &lt;element name="resource-principal" type="{}resource-principalType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identity-subjectType", namespace = "", propOrder = {
    "callerPrincipal",
    "resourcePrincipal"
})
public class IdentitySubjectType {

    @XmlElement(name = "caller-principal")
    protected CallerPrincipalType callerPrincipal;
    @XmlElement(name = "resource-principal", required = true)
    protected ResourcePrincipalType resourcePrincipal;

    /**
     * Gets the value of the callerPrincipal property.
     * 
     * @return
     *     possible object is
     *     {@link CallerPrincipalType }
     *     
     */
    public CallerPrincipalType getCallerPrincipal() {
        return callerPrincipal;
    }

    /**
     * Sets the value of the callerPrincipal property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallerPrincipalType }
     *     
     */
    public void setCallerPrincipal(CallerPrincipalType value) {
        this.callerPrincipal = value;
    }

    /**
     * Gets the value of the resourcePrincipal property.
     * 
     * @return
     *     possible object is
     *     {@link ResourcePrincipalType }
     *     
     */
    public ResourcePrincipalType getResourcePrincipal() {
        return resourcePrincipal;
    }

    /**
     * Sets the value of the resourcePrincipal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourcePrincipalType }
     *     
     */
    public void setResourcePrincipal(ResourcePrincipalType value) {
        this.resourcePrincipal = value;
    }

}
