//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:40 AM MSK 
//


package connectorj2eeengine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *    	 The inbound-resourceadapterType specifies additional information
 * 	 about an inbound resource adapter.
 *       
 * 
 * <p>Java class for inbound-resourceadapterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="inbound-resourceadapterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageadapter" type="{}messageadapterType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inbound-resourceadapterType", namespace = "", propOrder = {
    "messageadapter"
})
public class InboundResourceadapterType {

    protected MessageadapterType messageadapter;

    /**
     * Gets the value of the messageadapter property.
     * 
     * @return
     *     possible object is
     *     {@link MessageadapterType }
     *     
     */
    public MessageadapterType getMessageadapter() {
        return messageadapter;
    }

    /**
     * Sets the value of the messageadapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageadapterType }
     *     
     */
    public void setMessageadapter(MessageadapterType value) {
        this.messageadapter = value;
    }

}
