//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:40 AM MSK 
//


package connectorj2eeengine;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         TO DO          .
 *       
 * 
 * <p>Java class for pool-paramsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pool-paramsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="max-connections-number" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="max-time-to-wait-connection" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="expiration-control" type="{}expiration-controlType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pool-paramsType", namespace = "", propOrder = {
    "maxConnectionsNumber",
    "maxTimeToWaitConnection",
    "expirationControl"
})
public class PoolParamsType {

    @XmlElement(name = "max-connections-number", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxConnectionsNumber;
    @XmlElement(name = "max-time-to-wait-connection")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxTimeToWaitConnection;
    @XmlElement(name = "expiration-control")
    protected ExpirationControlType expirationControl;

    /**
     * Gets the value of the maxConnectionsNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxConnectionsNumber() {
        return maxConnectionsNumber;
    }

    /**
     * Sets the value of the maxConnectionsNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxConnectionsNumber(BigInteger value) {
        this.maxConnectionsNumber = value;
    }

    /**
     * Gets the value of the maxTimeToWaitConnection property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxTimeToWaitConnection() {
        return maxTimeToWaitConnection;
    }

    /**
     * Sets the value of the maxTimeToWaitConnection property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxTimeToWaitConnection(BigInteger value) {
        this.maxTimeToWaitConnection = value;
    }

    /**
     * Gets the value of the expirationControl property.
     * 
     * @return
     *     possible object is
     *     {@link ExpirationControlType }
     *     
     */
    public ExpirationControlType getExpirationControl() {
        return expirationControl;
    }

    /**
     * Sets the value of the expirationControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpirationControlType }
     *     
     */
    public void setExpirationControl(ExpirationControlType value) {
        this.expirationControl = value;
    }

}
