//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:40 AM MSK 
//


package connectorj2eeengine;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The resourceadapterType specifies additional information about the
 * 	   resource adapter. 
 *       
 * 
 * <p>Java class for resourceadapterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="resourceadapterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ra-jndi-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outbound-resourceadapter" type="{}outbound-resourceadapterType" minOccurs="0"/>
 *         &lt;element name="inbound-resourceadapter" type="{}inbound-resourceadapterType" minOccurs="0"/>
 *         &lt;element name="adminobjects" type="{}adminobjectsType" minOccurs="0"/>
 *         &lt;element name="loader-references" type="{}loader-referencesType" minOccurs="0"/>
 *         &lt;element name="workmanager-settings" type="{}workmanager-settingsType" minOccurs="0"/>
 *         &lt;element name="extended-properties" type="{}extended-propertiesType" minOccurs="0"/>
 *         &lt;element name="destination-name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="apply-updated" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "resourceadapterType", namespace = "", propOrder = {
    "raJndiName",
    "outboundResourceadapter",
    "inboundResourceadapter",
    "adminobjects",
    "loaderReferences",
    "workmanagerSettings",
    "extendedProperties",
    "destinationName"
})
public class ResourceadapterType {

    @XmlElement(name = "ra-jndi-name")
    protected java.lang.String raJndiName;
    @XmlElement(name = "outbound-resourceadapter")
    protected OutboundResourceadapterType outboundResourceadapter;
    @XmlElement(name = "inbound-resourceadapter")
    protected InboundResourceadapterType inboundResourceadapter;
    protected AdminobjectsType adminobjects;
    @XmlElement(name = "loader-references")
    protected LoaderReferencesType loaderReferences;
    @XmlElement(name = "workmanager-settings")
    protected WorkmanagerSettingsType workmanagerSettings;
    @XmlElement(name = "extended-properties")
    protected ExtendedPropertiesType extendedProperties;
    @XmlElement(name = "destination-name")
    protected java.lang.String destinationName;
    @XmlAttribute(name = "apply-updated")
    @XmlSchemaType(name = "anySimpleType")
    protected java.lang.String applyUpdated;

    /**
     * Gets the value of the raJndiName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getRaJndiName() {
        return raJndiName;
    }

    /**
     * Sets the value of the raJndiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setRaJndiName(java.lang.String value) {
        this.raJndiName = value;
    }

    /**
     * Gets the value of the outboundResourceadapter property.
     * 
     * @return
     *     possible object is
     *     {@link OutboundResourceadapterType }
     *     
     */
    public OutboundResourceadapterType getOutboundResourceadapter() {
        return outboundResourceadapter;
    }

    /**
     * Sets the value of the outboundResourceadapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutboundResourceadapterType }
     *     
     */
    public void setOutboundResourceadapter(OutboundResourceadapterType value) {
        this.outboundResourceadapter = value;
    }

    /**
     * Gets the value of the inboundResourceadapter property.
     * 
     * @return
     *     possible object is
     *     {@link InboundResourceadapterType }
     *     
     */
    public InboundResourceadapterType getInboundResourceadapter() {
        return inboundResourceadapter;
    }

    /**
     * Sets the value of the inboundResourceadapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundResourceadapterType }
     *     
     */
    public void setInboundResourceadapter(InboundResourceadapterType value) {
        this.inboundResourceadapter = value;
    }

    /**
     * Gets the value of the adminobjects property.
     * 
     * @return
     *     possible object is
     *     {@link AdminobjectsType }
     *     
     */
    public AdminobjectsType getAdminobjects() {
        return adminobjects;
    }

    /**
     * Sets the value of the adminobjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdminobjectsType }
     *     
     */
    public void setAdminobjects(AdminobjectsType value) {
        this.adminobjects = value;
    }

    /**
     * Gets the value of the loaderReferences property.
     * 
     * @return
     *     possible object is
     *     {@link LoaderReferencesType }
     *     
     */
    public LoaderReferencesType getLoaderReferences() {
        return loaderReferences;
    }

    /**
     * Sets the value of the loaderReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoaderReferencesType }
     *     
     */
    public void setLoaderReferences(LoaderReferencesType value) {
        this.loaderReferences = value;
    }

    /**
     * Gets the value of the workmanagerSettings property.
     * 
     * @return
     *     possible object is
     *     {@link WorkmanagerSettingsType }
     *     
     */
    public WorkmanagerSettingsType getWorkmanagerSettings() {
        return workmanagerSettings;
    }

    /**
     * Sets the value of the workmanagerSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkmanagerSettingsType }
     *     
     */
    public void setWorkmanagerSettings(WorkmanagerSettingsType value) {
        this.workmanagerSettings = value;
    }

    /**
     * Gets the value of the extendedProperties property.
     * 
     * @return
     *     possible object is
     *     {@link ExtendedPropertiesType }
     *     
     */
    public ExtendedPropertiesType getExtendedProperties() {
        return extendedProperties;
    }

    /**
     * Sets the value of the extendedProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtendedPropertiesType }
     *     
     */
    public void setExtendedProperties(ExtendedPropertiesType value) {
        this.extendedProperties = value;
    }

    /**
     * Gets the value of the destinationName property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getDestinationName() {
        return destinationName;
    }

    /**
     * Sets the value of the destinationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setDestinationName(java.lang.String value) {
        this.destinationName = value;
    }

    /**
     * Gets the value of the applyUpdated property.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String }
     *     
     */
    public java.lang.String getApplyUpdated() {
        return applyUpdated;
    }

    /**
     * Sets the value of the applyUpdated property.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String }
     *     
     */
    public void setApplyUpdated(java.lang.String value) {
        this.applyUpdated = value;
    }

}
