//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 06:58:40 AM MSK 
//


package connectorj2eeengine;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for workmanager-settingsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="workmanager-settingsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="max-thread-count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="start-thread-timeout" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "workmanager-settingsType", namespace = "", propOrder = {
    "maxThreadCount",
    "startThreadTimeout"
})
public class WorkmanagerSettingsType {

    @XmlElement(name = "max-thread-count")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maxThreadCount;
    @XmlElement(name = "start-thread-timeout")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger startThreadTimeout;

    /**
     * Gets the value of the maxThreadCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxThreadCount() {
        return maxThreadCount;
    }

    /**
     * Sets the value of the maxThreadCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxThreadCount(BigInteger value) {
        this.maxThreadCount = value;
    }

    /**
     * Gets the value of the startThreadTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStartThreadTimeout() {
        return startThreadTimeout;
    }

    /**
     * Sets the value of the startThreadTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStartThreadTimeout(BigInteger value) {
        this.startThreadTimeout = value;
    }

}
