//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.05.19 at 08:17:03 PM MSK 
//


package application13;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "connectorOrEjbOrJavaOrWeb",
    "altDd"
})
@XmlRootElement(name = "module")
public class Module {

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;
    @XmlElements({
        @XmlElement(name = "connector", required = true, type = Connector.class),
        @XmlElement(name = "ejb", required = true, type = Ejb.class),
        @XmlElement(name = "java", required = true, type = Java.class),
        @XmlElement(name = "web", required = true, type = Web.class)
    })
    protected List<Object> connectorOrEjbOrJavaOrWeb;
    @XmlElement(name = "alt-dd")
    protected AltDd altDd;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the connectorOrEjbOrJavaOrWeb property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the connectorOrEjbOrJavaOrWeb property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConnectorOrEjbOrJavaOrWeb().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Connector }
     * {@link Ejb }
     * {@link Java }
     * {@link Web }
     * 
     * 
     */
    public List<Object> getConnectorOrEjbOrJavaOrWeb() {
        if (connectorOrEjbOrJavaOrWeb == null) {
            connectorOrEjbOrJavaOrWeb = new ArrayList<Object>();
        }
        return this.connectorOrEjbOrJavaOrWeb;
    }

    /**
     * Gets the value of the altDd property.
     * 
     * @return
     *     possible object is
     *     {@link AltDd }
     *     
     */
    public AltDd getAltDd() {
        return altDd;
    }

    /**
     * Sets the value of the altDd property.
     * 
     * @param value
     *     allowed object is
     *     {@link AltDd }
     *     
     */
    public void setAltDd(AltDd value) {
        this.altDd = value;
    }

}
